server:
  servlet:
    context-path: /ServiceReportWeb
    session:
      timeout: 1800s
  undertow:
    #    设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    #    不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 4
    #    以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    #    每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    #    是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
  tomcat:
    uri-encoding: utf-8
  port: 8081
spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
    auto: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  #  MyBatis 配置文件位置，如果您有单独的 MyBatis 配置，请将其路径配置到 configLocation 中。
  #  config-location: classpath:mybatis-config.xml

  #  MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  mapper-locations: classpath*:mapper/*Mapper.xml

  #  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）。
  type-aliases-package: com.zhongzhou.*.entity

  #  该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  #  type-aliases-super-type: java.lang.Object

  #  枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  #  type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
  #  TypeHandler 扫描路径，如果配置了该属性，SqlSessionFactoryBean 会把该包下面的类注册为对应的 TypeHandler。
  #  type-handlers-package: com.baomidou.mybatisplus.samples.quickstart.handler

  #  启动时是否检查 MyBatis XML 文件的存在，默认不检查。
  check-config-location: false

  #  通过该属性可指定 MyBatis 的执行器，MyBatis 的执行器总共有三种：
  #  ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
  #  ExecutorType.REUSE：该执行器类型会复用预处理语句（PreparedStatement）
  #  ExecutorType.BATCH：该执行器类型会批量执行所有的更新语句
  executor-type: simple

  #  指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署。
  #  configuration-properties: classpath:mybatis/config.properties

  configuration:
    #    全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true。
    cache-enabled: false
    #    是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    #    返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: id_worker
      logic-not-delete-value: 0
      logic-delete-value: 1
#      全局删除字段
#      logic-delete-field: deleteFlag
logging:
  config: classpath:logback-spring.xml
  file:
    max-size: 50MB
    max-history: 30
    path: /log/ServiceReportWeb